#!/usr/bin/env python3
"""Build a starter fact-check inventory from an article markdown file.

Walks the body, extracts the claim-shapes that the fact-check pass cares
about (numbers, percentages, dates, named entities in 「」 / "" quotes,
explicit URLs already cited), and emits a Markdown checklist file the
editor can fill out.

This is NOT a verifier. It does not actually check facts. It just turns
"the editor has to remember every claim" into "the editor has to walk a
list," which is the difference between fact-check getting done and not.

Usage:
    fact_check_inventory.py <article.md>
        > <slug>-fact-check.md

The output is meant to be filled in manually with the literal source
quote and a pass/fail mark, then attached to the editorial PR.
"""
from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path


# ---------------------------------------------------------------------------
# claim extraction
# ---------------------------------------------------------------------------

# Numbers worth a checklist row — any digit-bearing token, percentages,
# pp/percentage points, currency, and round multipliers like "万" / "亿".
NUMBER_RE = re.compile(
    r"""
    (?:
        \d+(?:[.,]\d+)?\s*(?:%|pp|个百分点|百分点|GW|MW|kW|B|M|K|亿|万|千)
        |
        \d+(?:[.,]\d+)?\s*[-/–]\s*\d+(?:[.,]\d+)?
        |
        \d{1,3}(?:[,\s]\d{3})+
        |
        \$\s*\d+(?:[.,]\d+)?(?:\s*[BMKT])?
        |
        \d+(?:[.,]\d+)?
    )
    """,
    re.VERBOSE,
)

# A specific calendar date or month/day phrase.
DATE_RE = re.compile(
    r"""
    (?:
        \d{4}[-/]\d{1,2}[-/]\d{1,2}
        |
        \d{1,2}\s*月\s*\d{1,2}\s*日
        |
        \d{4}\s*年\s*\d{1,2}\s*月
        |
        (?:January|February|March|April|May|June|July|August|September|October|November|December)\s+\d{1,2}
    )
    """,
    re.VERBOSE | re.IGNORECASE,
)

# Direct quote (Chinese 「」, "" or English "...") with at least 4 chars.
QUOTE_RE = re.compile(r"""[「""]([^「」""]{4,})[」""]""")

# Inline markdown link target — useful as "claims that DO have a citation".
LINK_RE = re.compile(r"\[([^\]]+)\]\(([^)\s]+)\)")


@dataclass
class Claim:
    paragraph_idx: int
    text: str          # the surrounding sentence
    matched: str       # the specific token that triggered the row
    kind: str          # "number" | "date" | "quote"


def split_paragraphs(body: str) -> list[str]:
    return [p.strip() for p in re.split(r"\n\s*\n", body.strip()) if p.strip()]


def extract_claims(body: str) -> list[Claim]:
    paragraphs = split_paragraphs(body)
    out: list[Claim] = []

    for idx, para in enumerate(paragraphs, start=1):
        # Skip image lines and frontmatter-style lines
        if para.startswith("!["):
            continue

        # Walk sentence boundaries inside the paragraph for tighter context.
        sentences = re.split(r"(?<=[。！？.!?])\s*", para)
        for sentence in sentences:
            if not sentence.strip():
                continue

            for m in NUMBER_RE.finditer(sentence):
                out.append(Claim(
                    paragraph_idx=idx,
                    text=sentence.strip()[:120],
                    matched=m.group(0).strip(),
                    kind="number",
                ))

            for m in DATE_RE.finditer(sentence):
                out.append(Claim(
                    paragraph_idx=idx,
                    text=sentence.strip()[:120],
                    matched=m.group(0).strip(),
                    kind="date",
                ))

            for m in QUOTE_RE.finditer(sentence):
                quote = m.group(1).strip()
                if len(quote) < 4:
                    continue
                out.append(Claim(
                    paragraph_idx=idx,
                    text=sentence.strip()[:120],
                    matched=quote[:80],
                    kind="quote",
                ))

    return out


def cited_urls(body: str) -> list[str]:
    return sorted({m.group(2) for m in LINK_RE.finditer(body)})


# ---------------------------------------------------------------------------
# rendering
# ---------------------------------------------------------------------------

def render(claims: list[Claim], urls: list[str], slug: str) -> str:
    lines = [
        f"# Fact-check inventory — {slug}",
        "",
        "Generated by `fact_check_inventory.py`. Fill in the **Source quote** ",
        "column with the literal sentence from the source, then mark Match? as ",
        "✅ or ❌. See `references/fact-check.md` for the rules.",
        "",
        "## Claims to verify",
        "",
        "| # | Para | Kind | Claim token | Sentence (truncated) | Source URL | Source quote (verbatim) | Match? |",
        "|---|------|------|-------------|----------------------|------------|-------------------------|--------|",
    ]
    for n, c in enumerate(claims, start=1):
        # Escape pipe characters in any user content
        text = c.text.replace("|", "\\|")
        matched = c.matched.replace("|", "\\|")
        lines.append(f"| {n} | p{c.paragraph_idx} | {c.kind} | `{matched}` | {text} |  |  |  |")

    if not claims:
        lines.append("| — | — | — | — | (no claim shapes found — double-check that this article has any verifiable content) | — | — | — |")

    lines.append("")
    lines.append("## URLs already cited inline")
    lines.append("")
    if urls:
        for u in urls:
            lines.append(f"- {u}")
    else:
        lines.append("_(none — a `data-piece` article without inline source links is suspicious; revisit before publish.)_")

    lines.append("")
    lines.append("## Pre-publish gate")
    lines.append("")
    lines.append("- [ ] Every row above has either a verbatim Source quote or has been removed from the prose.")
    lines.append("- [ ] Denominators are intact: any `X%` claim names what X% is of.")
    lines.append("- [ ] No causal upgrade (`correlates with` was not promoted to `causes`).")
    lines.append("- [ ] Time window of every numeric claim matches the source's window.")
    lines.append("- [ ] Direct quotes are byte-equal to the source (no paraphrase wrapped in quote marks).")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def parse_frontmatter_and_body(text: str) -> tuple[dict[str, str], str]:
    m = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.DOTALL)
    if not m:
        return {}, text
    head, body = m.group(1), m.group(2).lstrip("\n")
    fm: dict[str, str] = {}
    for line in head.splitlines():
        if ":" in line:
            k, v = line.split(":", 1)
            fm[k.strip()] = v.strip()
    return fm, body


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("markdown")
    args = ap.parse_args()

    text = Path(args.markdown).read_text(encoding="utf-8")
    fm, body = parse_frontmatter_and_body(text)
    slug = fm.get("slug", Path(args.markdown).stem)

    claims = extract_claims(body)
    urls = cited_urls(body)

    sys.stdout.write(render(claims, urls, slug))
    sys.stdout.write("\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
